import type { CourseModule } from '../types';

export const COURSE_MODULES: CourseModule[] = [
  {
    id: 'setting-financial-goals',
    title: 'Setting Financial Goals & Assessing Your Situation',
    description: 'Dream big and turn those dreams into actionable financial goals by assessing your current financial situation.',
    goals: [
      'Determine and set personal financial goals.',
      'Understand what influences financial decisions.',
      'Create a personal balance sheet.',
      'Turn dreams into concrete goals.',
    ],
    keyConcepts: ['Financial Goals', 'Personal Balance Sheet', 'Values', 'Money Personalities'],
    contents: [
      { type: 'Use Case', title: 'If Money Were No Object ...', duration: '2 min' },
      { type: 'Reading', title: 'Dream Big', duration: '6 min' },
      { type: 'Discussion Prompt', title: 'Dream Big – Create a Picture of Where You Want to Be', duration: '5-20 min' },
      { type: 'Reading', title: 'Belize for Spring Break?', duration: '2 min' },
      { type: 'Lecture Video', title: 'What Influences Our Financial Decisions?', duration: '12 min' },
      { type: 'Reading', title: 'Education, Retirement, or Fun?', duration: '3 min' },
      { type: 'Reading', title: 'Exploring Money Personalities Further', duration: '10 min' },
      { type: 'Reading', title: 'Where Are You Now?', duration: '9 min' },
      { type: 'Discussion Prompt', title: 'Your Personal Balance Sheet', duration: '20 min' },
      { type: 'Reading', title: 'Turning Dreams into Goals', duration: '7 min' },
    ],
  },
  {
    id: 'budgeting-and-cash-flow',
    title: 'Budgeting and Cash Flow Management',
    description: 'Learn to create and stick to a budget, manage your cash flow, and understand different financial services.',
    goals: [
      'Implement the process of personal budgeting.',
      'Learn to avoid overspending.',
      'Understand various financial services and cash alternatives.',
      'Identify the pros and cons of using credit cards.',
    ],
    keyConcepts: ['Budgeting', 'Cash Flow', 'Financial Services', 'Credit Cards', 'Overspending'],
    contents: [
      { type: 'Use Case', title: 'Do You Keep Track of Your Monthly Expenses?', duration: '2 min' },
      { type: 'Reading', title: 'Budgeting Overview', duration: '14 min' },
      { type: 'Use Case', title: 'How Can You Avoid Overspending?', duration: '2 min' },
      { type: 'Interview', title: 'Investment Advisor Interview', duration: '7 min' },
      { type: 'Reading', title: 'Creating a Budget', duration: '2 min' },
      { type: 'Reading', title: 'Financial Services', duration: '14 min' },
      { type: 'Reading', title: 'Alternatives to Cash', duration: '15 min' },
      { type: 'Use Case', title: 'What Are the Pros and Cons of Using a Credit Card?', duration: '2 min' },
      { type: 'Discussion Prompt', title: 'Preferences for Cash Flow Management', duration: '20 min' },
    ],
  },
  {
    id: 'saving-strategies',
    title: 'Saving Strategies',
    description: 'Discover why saving is crucial, how to start, and how to overcome common barriers to building a solid savings habit.',
    goals: [
      'Understand the importance of saving money.',
      'Learn how to start saving effectively.',
      'Overcome barriers to successful savings strategies.',
      'Write SMART savings goals.',
    ],
    keyConcepts: ['Emergency Fund', 'Savings Habit', 'SMART Goals', 'Barriers to Saving'],
    contents: [
        { type: 'Street Interview Video', title: 'Do You Set Aside Money for Emergencies?', duration: '1 min' },
        { type: 'Lecture Video', title: 'Why Save Money?', duration: '8 min' },
        { type: 'Lecture Video', title: 'How to Start Saving Money', duration: '10 min' },
        { type: 'Discussion Prompt', title: 'Should Young Adults Save Money?', duration: '10 min' },
        { type: 'Vignette Video', title: 'Set a Savings Goal', duration: '2 min' },
        { type: 'Lecture Video', title: 'Build a Savings Habit', duration: '5 min' },
        { type: 'Optional Peer-Review', title: 'Write a SMART Goal', duration: '20 min' },
        { type: 'Reading', title: 'America Saves', duration: '15 min' },
        { type: 'Street Interview Video', title: 'What Are Some Barriers to Saving Money?', duration: '1 min' },
        { type: 'Lecture Video', title: 'Barriers to Saving', duration: '8 min' },
    ],
  },
  {
    id: 'time-value-of-money',
    title: 'Time Value of Money',
    description: 'Understand the powerful concept of how time affects the value of money—a key to building wealth.',
    goals: [
      'Define factors like inflation and opportunity cost.',
      'Understand how interest rates and time affect future value.',
      'Know which time value formula to use for different saving strategies.',
      'Visualize the concept of "time value of money".',
    ],
    keyConcepts: ['Inflation', 'Opportunity Cost', 'Interest Rates', 'Compounding', 'Present Value', 'Future Value'],
    contents: [
      { type: 'Lecture Video', title: 'Time Value of Money', duration: '14 min' },
      { type: 'Discussion Prompt', title: 'What Does the Time Value of Money Look Like?', duration: '30 min' },
    ],
  },
  {
    id: 'borrowing-and-credit',
    title: 'Borrowing and Credit',
    description: 'Learn about loans, credit, and how to manage them wisely to build a positive financial future.',
    goals: [
        'Identify the advantages and disadvantages of borrowing.',
        'Reflect on personal attitudes towards debt.',
        'Understand a loan amortization schedule.',
        'Understand credit reports and scores.',
    ],
    keyConcepts: ['Loan Contracts', 'Credit Lines', 'Amortization', 'Credit Report', 'Credit Score'],
    contents: [
        { type: 'Lecture Video', title: 'Loans and Consumer Credit', duration: '5 min' },
        { type: 'Lecture Video', title: 'Borrowing and Credit: Pros and Cons', duration: '8 min' },
        { type: 'Lecture Video', title: 'Loan Amortization Part One', duration: '5 min' },
        { type: 'Lecture Video', title: 'Loan Amortization Part Two', duration: '6 min' },
        { type: 'Lecture Video', title: 'Loan Amortization Part Three', duration: '5 min' },
        { type: 'Discussion Prompt', title: 'Personal Attitudes Towards Borrowing and Debt', duration: '20 min' },
        { type: 'Vignette Video', title: 'What Is a Credit Report?', duration: '2 min' },
        { type: 'Lecture Video', title: 'Credit Reports', duration: '11 min' },
        { type: 'Lecture Video', title: 'Credit Score', duration: '10 min' },
        { type: 'Loan Denial Testimonial', title: 'Bad Credit History', duration: '2 min' },
        { type: 'Loan Denial Testimonial', title: 'No Credit History', duration: '1 min' },
        { type: 'Loan Denial Testimonial', title: 'Identity Theft', duration: '2 min' },
        { type: 'Discussion Prompt', title: 'Monitoring Your Credit Information', duration: '20 min' },
    ],
  },
  {
    id: 'investing',
    title: 'Investing',
    description: 'Get introduced to the world of investing, from basic terms and strategies to understanding risk and diversification.',
    goals: [
        'Define stocks, bonds, and mutual funds.',
        'Explain different types of investment risk.',
        'Understand how to diversify investments.',
        'Explain the advantages of saving for retirement.',
    ],
    keyConcepts: ['Stocks', 'Bonds', 'Mutual Funds', 'Risk', 'Diversification', 'Retirement Plans'],
    contents: [
        { type: 'Street Interview Video', title: 'How Would You Invest $100,000?', duration: '1 min' },
        { type: 'Lecture Video', title: 'Introduction to Investing Terms', duration: '13 min' },
        { type: 'Discussion Prompt', title: 'Key Investing Concepts', duration: '5 min' },
        { type: 'Lecture Video', title: 'Understanding Investment Risk', duration: '6 min' },
        { type: 'Street Interview Video', title: 'What Does It Mean to Diversify Investments?', duration: '1 min' },
        { type: 'Lecture Video', title: 'Diversify Your Investments', duration: '9 min' },
        { type: 'Reading', title: 'Building on Your Knowledge', duration: '10 min' },
        { type: 'Vignette Video', title: 'When to Start Saving for Retirement?', duration: '2 min' },
        { type: 'Discussion Prompt', title: 'When Should People Start Saving for Retirement?', duration: '10 min' },
        { type: 'Lecture Video', title: 'Investing Tips for Young Adults', duration: '13 min' },
        { type: 'Quiz', title: 'Investing', duration: '35 min' },
    ],
  },
  {
    id: 'risk-management',
    title: 'Risk Management',
    description: 'Focuses on the role of risk management within a financial plan, with a specific focus on insurance.',
    goals: [
        'Discuss the importance of risk management.',
        'Understand the role of insurance in a risk plan.',
        'Describe a life insurance needs assessment.',
        'Describe a personal risk tolerance assessment.',
    ],
    keyConcepts: ['Risk Management', 'Insurance', 'Life Insurance', 'Risk Tolerance'],
    contents: [
        { type: 'Lecture Video', title: 'Risk Management Overview', duration: '12 min' },
        { type: 'Discussion Prompt', title: 'Risk Tolerance Assessment', duration: '20 min' },
        { type: 'Street Interview Video', title: 'Why Do You Buy Insurance?', duration: '1 min' },
        { type: 'Lecture Video', title: 'Insurance Basics', duration: '21 min' },
        { type: 'Street Interview Video', title: 'What Determines the Cost of Insurance?', duration: '1 min' },
        { type: 'Lecture Video', title: 'Life Insurance', duration: '13 min' },
        { type: 'Vignette Video', title: 'Are You Ready for Life Insurance?', duration: '4 min' },
        { type: 'Lecture Video', title: 'Insurance Risk Panel Discussion', duration: '15 min' },
        { type: 'Discussion Prompt', title: 'Life Insurance Needs Assessment', duration: '20 min' },
    ],
  },
];